### ISSUE TITLE
手札が更新されない

### ISSUE THREAD

**Issue by haruya3** [EgameProject/egameproject#2]
手札が更新されるように修正してください

**Comment by teraaaa26** [comment]
僕がやります

**Comment by haruya3** [comment]
手札の変数更新されてる。Imageの更新ができてない。

**Comment by teraaaa26** [comment]
civilのカードが手札に表示されていない。

**Comment by haruya3** [comment]
civilは最初にしかimageに入れてないから、setCardでcivilもimageに入れるコードを書かないといけない。ごり押しならすぐかけそうだけど、スマートじゃない。

**Comment by haruya3** [comment]
setNextRoundでcivilをimageにまた、セットすればいい。

**Comment by teraaaa26** [comment]
setNextRounを変えることで手札の更新はできた。civil同士の時に次の手札が出せない。
