### ISSUE TITLE
引き分けの時なにも起きない

### ISSUE THREAD

**Issue by haruya3** [EgameProject/egameproject#6]
引き分けの時、drawがtrueになるときとfalseになるときの位置と、下のif分に引き分けの時も実行されてしまうのが問題点

**Comment by teraaaa26** [comment]
勝利カウントの判定を移動して、それぞぞれのの判定を移動して、カードによってのそれぞれの勝敗判定のところに入れればよいが、あまりに無理やりすぎるし、スマートではない。

**Comment by teraaaa26** [comment]
勝利カウントのelseのところをelse ifにして条件にdrawがfalseであるときに次へを押せるようにし、drawをカードの勝敗判定のところでtureからfalseに移行するようにしたらできる。
